# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Blackcart Staging"
client_id = "b6aa42c5ed32eacc19e8ef2c37d662d6"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_cart_transforms,write_cart_transforms,unauthenticated_read_checkouts,unauthenticated_write_checkouts,read_checkouts,write_checkouts,read_customer_payment_methods,write_customer_payment_methods,unauthenticated_read_customers,unauthenticated_write_customers,read_customers,write_customers,unauthenticated_read_customer_tags,read_discounts,write_discounts,read_draft_orders,write_draft_orders,read_files,write_files,read_fulfillments,write_fulfillments,read_gift_cards,write_gift_cards,read_inventory,write_inventory,read_locales,write_locales,read_locations,write_locations,read_markets,write_markets,unauthenticated_read_metaobjects,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_orders,write_orders,read_payment_mandate,write_payment_mandate,read_payment_terms,write_payment_terms,read_price_rules,write_price_rules,read_products,write_products,unauthenticated_read_product_listings,read_product_listings,unauthenticated_read_product_tags,read_purchase_options,write_purchase_options,read_reports,write_reports,read_returns,write_returns,unauthenticated_read_selling_plans,read_own_subscription_contracts,write_own_subscription_contracts,read_themes,write_themes,read_translations,read_order_edits,write_order_edits"
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
